/** Byte-preserving static R04 display derivative. No CAD/source overwrite. */
import fs from 'node:fs';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {Vector3,Matrix3,Quaternion} from 'three';
const project=fileURLToPath(new URL('../../',import.meta.url)).replace(/\/$/,''),out=process.env.ATLAS_M6_OUTPUT||'/tmp/exo-m6-hands';
const inputs={static:project+'/public/assets/v04/atlas-r04.glb',old:project+'/public/assets/v04/motion-m3/atlas-motion.glb',m6:out+'/atlas-motion.glb'};
function readGLB(path){let b=fs.readFileSync(path),n=b.readUInt32LE(12);return {bytes:b,json:JSON.parse(b.subarray(20,20+n)),bin:b.subarray(28+n)}}
async function load(d){return(await new GLTFLoader().parseAsync(d.bytes.buffer.slice(d.bytes.byteOffset,d.bytes.byteOffset+d.bytes.byteLength),'')).scene}
const src=readGLB(inputs.static),old=readGLB(inputs.old),m6=readGLB(inputs.m6),[oldScene,m6Scene]=await Promise.all([load(old),load(m6)]);oldScene.updateMatrixWorld(true);m6Scene.updateMatrixWorld(true);
let bones={};m6Scene.traverse(o=>{if(o.isBone)bones[o.name]=o});const rig=JSON.parse(fs.readFileSync(out+'/rig.json','utf8')),k=rig.fingerSolver,grip=.31,r=k.closedRadius+(k.openRadius-k.closedRadius)*grip,dx=r-k.baseRadial,dz=k.contactAxial-k.baseAxial,L1=k.proxLength,L2=k.distLength,q2=-Math.acos((dx*dx+dz*dz-L1*L1-L2*L2)/(2*L1*L2)),q1=Math.atan2(dx,dz)-Math.atan2(L2*Math.sin(q2),L1+L2*Math.cos(q2));
for(const side of ['L','R'])for(const f of rig.mechanical[side].fingers){bones[f.bones[0]].quaternion.setFromAxisAngle(new Vector3(...f.rotationAxis),q1-k.proxRestAngle);bones[f.bones[1]].quaternion.setFromAxisAngle(new Vector3(...f.rotationAxis),q2-k.distRestAngle);}m6Scene.updateMatrixWorld(true);
function ancestorMetadata(o){for(let p=o;p;p=p.parent)if(p.userData?.module)return p.userData;return {}}
function triangleKey(a,b,c){return [a,b,c].map(v=>[v.x,v.y,v.z].map(x=>Math.round(x*1e4)).join(',')).sort().join('|')}
const removeTriangles=new Map(),triangleBuckets=new Map(),oldTriangles=[];let oldPalmTriangleCount=0,maxMatchedVertexError=0;
function bucket(v){return [Math.floor(v.x*1000),Math.floor(v.y*1000),Math.floor(v.z*1000)]}
function matchTriangle(v){const c=v[0].clone().add(v[1]).add(v[2]).multiplyScalar(1/3),b=bucket(c);for(let x=-1;x<=1;x++)for(let y=-1;y<=1;y++)for(let z=-1;z<=1;z++){for(const rec of triangleBuckets.get([b[0]+x,b[1]+y,b[2]+z].join(','))??[]){if(rec.matched)continue;let worst=0,valid=true,seen=new Set();for(const p of v){let bi=-1,bd=Infinity;for(let i=0;i<3;i++){const d=p.distanceTo(rec.v[i]);if(!seen.has(i)&&d<bd){bi=i;bd=d}}if(bd>2e-6){valid=false;break}seen.add(bi);worst=Math.max(worst,bd)}if(valid){rec.matched=true;maxMatchedVertexError=Math.max(maxMatchedVertexError,worst);return true}}}return false}

oldScene.traverse(o=>{if(!o.isMesh)return;const meta=ancestorMetadata(o);if(meta.module!=='A04'||meta.layer!=='frame'||!String(meta.motionBinding).startsWith('exowrist_'))return;const g=o.geometry,p=g.attributes.position,idx=g.index;for(let i=0;i<(idx?.count??p.count);i+=3){const v=[0,1,2].map(j=>new Vector3().fromBufferAttribute(p,idx?idx.getX(i+j):i+j).applyMatrix4(o.matrixWorld));const centre=v[0].clone().add(v[1]).add(v[2]).multiplyScalar(1/3),key=bucket(centre).join(','),rec={v,matched:false};if(!triangleBuckets.has(key))triangleBuckets.set(key,[]);triangleBuckets.get(key).push(rec);oldTriangles.push(rec);oldPalmTriangleCount++}});
const componentSizes={5120:1,5121:1,5122:2,5123:2,5125:4,5126:4},typeSizes={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT4:16};
function accessor(i){const a=src.json.accessors[i],v=src.json.bufferViews[a.bufferView],bytes=componentSizes[a.componentType],size=typeSizes[a.type],start=(v.byteOffset||0)+(a.byteOffset||0),stride=v.byteStride||bytes*size,dv=new DataView(src.bin.buffer,src.bin.byteOffset,src.bin.length);return {a,size,get(row,col=0){let at=start+row*stride+col*bytes;return a.componentType===5126?dv.getFloat32(at,true):a.componentType===5125?dv.getUint32(at,true):a.componentType===5123?dv.getUint16(at,true):dv.getUint8(at)},bytes:src.bin.subarray(start,start+(a.count-1)*stride+bytes*size)}}
const j=structuredClone(src.json);let chunks=[src.bin.subarray(0,src.json.buffers[0].byteLength)];let length=chunks[0].length;
function append(data,target){const pad=(4-length%4)%4;if(pad){chunks.push(Buffer.alloc(pad));length+=pad}const view=j.bufferViews.length;j.bufferViews.push({buffer:0,byteOffset:length,byteLength:data.byteLength,...(target?{target}:{})});chunks.push(Buffer.from(data.buffer,data.byteOffset,data.byteLength));length+=data.byteLength;return view}
function addAccessor(data,type,componentType,target,min,max){const view=append(data,target),i=j.accessors.length;j.accessors.push({bufferView:view,componentType,count:data.length/typeSizes[type],type,...(min?{min,max}:{})});return i}
const jawNodeIndices=new Set(),removedNodeNames=[],modified=[];let removedMatched=0;
for(let ni=0;ni<j.nodes.length;ni++){const node=j.nodes[ni],e=node.extras||{};if(e.module!=='A04')continue;if(['A04_PARALLEL_JAW','A04_CONTACT_PAD'].includes(e.cadPart)){jawNodeIndices.add(ni);removedNodeNames.push(node.name);continue}if(e.layer!=='frame')continue;const mesh=j.meshes[node.mesh];for(let pi=0;pi<mesh.primitives.length;pi++){const primitive=mesh.primitives[pi],pos=accessor(primitive.attributes.POSITION),indices=primitive.indices===undefined?null:accessor(primitive.indices);const count=indices?indices.a.count:pos.a.count,kept=[];let removed=0;for(let n=0;n<count;n+=3){const ids=[0,1,2].map(k=>indices?indices.get(n+k):n+k),v=ids.map(id=>new Vector3(pos.get(id,0),pos.get(id,1),pos.get(id,2))),matches=matchTriangle(v);if(matches){removed++;removedMatched++}else kept.push(...ids)}if(removed){primitive.indices=addAccessor(new Uint32Array(kept),'SCALAR',5125,34963);modified.push({node:node.name,mesh:node.mesh,primitive:pi,originalTriangles:count/3,removedTriangles:removed,retainedTriangles:kept.length/3,attributesUnchanged:true});}}}
const missing=oldTriangles.filter(t=>!t.matched).length;if(missing)throw Error(`Cannot guarantee selective replacement: ${missing}/${oldPalmTriangleCount} palm triangles did not match`);
// Physically remove old jaw nodes from active scene and JSON, keeping buffers,
// accessors and all other geometry byte-for-byte. Old unused mesh descriptors
// and bytes are harmless archival data; no removed node can instantiate them.
const nodeRemap=new Map();j.nodes=j.nodes.filter((n,i)=>{if(jawNodeIndices.has(i))return false;nodeRemap.set(i,nodeRemap.size);return true});
for(const node of j.nodes)if(node.children)node.children=node.children.filter(i=>!jawNodeIndices.has(i)).map(i=>nodeRemap.get(i));for(const scene of j.scenes)scene.nodes=scene.nodes.filter(i=>!jawNodeIndices.has(i)).map(i=>nodeRemap.get(i));
const added=[];m6Scene.traverse(o=>{if(!o.isMesh)return;const meta=ancestorMetadata(o);if(meta.module!=='A04')return;const bind=String(meta.motionBinding||'');const isNew=o.name.startsWith('A04__M6__'),isAdapter=meta.layer==='articulation'&&bind.startsWith('exowrist_');if(!isNew&&!isAdapter)return;const g=o.geometry,attrs={},normalMatrix=new Matrix3().getNormalMatrix(o.matrixWorld);for(const [name,attr]of Object.entries(g.attributes)){if(['skinIndex','skinWeight'].includes(name))continue;const map={position:'POSITION',normal:'NORMAL',uv:'TEXCOORD_0',uv1:'TEXCOORD_1',tangent:'TANGENT',color:'COLOR_0'},semantic=map[name];if(!semantic)continue;const data=new Float32Array(attr.count*attr.itemSize);let min=Array(attr.itemSize).fill(Infinity),max=Array(attr.itemSize).fill(-Infinity);for(let i=0;i<attr.count;i++){let value;if(name==='position')value=new Vector3().fromBufferAttribute(attr,i).applyMatrix4(o.matrixWorld).toArray();else if(name==='normal')value=new Vector3().fromBufferAttribute(attr,i).applyMatrix3(normalMatrix).normalize().toArray();else value=Array.from({length:attr.itemSize},(_,c)=>attr.array[i*attr.itemSize+c]);for(let c=0;c<attr.itemSize;c++){data[i*attr.itemSize+c]=value[c];min[c]=Math.min(min[c],data[i*attr.itemSize+c]);max[c]=Math.max(max[c],data[i*attr.itemSize+c]);}}attrs[semantic]=addAccessor(data,'VEC'+attr.itemSize,5126,34962,name==='position'?min:undefined,name==='position'?max:undefined)}let material=j.materials.findIndex(m=>m.name===o.material.name);if(material<0){material=j.materials.length;const source=m6.json.materials.find(m=>m.name===o.material.name);if(!source)throw Error('Material missing '+o.material.name);j.materials.push(structuredClone(source));}const prim={attributes:attrs,material};if(g.index)prim.indices=addAccessor(new Uint32Array(g.index.array),'SCALAR',5125,34963);const mi=j.meshes.length;j.meshes.push({name:o.name,primitives:[prim]});const name='STATIC_M6__'+o.name,ni=j.nodes.length;
const layer=o.material.name.includes('elastomer')?'soft':o.material.name.includes('index')?'shell':'frame';j.nodes.push({name,mesh:mi,extras:{...meta,module:'A04',side:meta.side,layer,originalDisplayLayer:meta.layer,displayOnlyAddition:true,displayRevision:'M6',motionBinding:bind,bakedGrip:grip}});j.scenes[j.scene??0].nodes.push(ni);added.push({node:name,sourceNode:o.name,side:meta.side,layer,binding:bind,vertices:g.attributes.position.count,triangles:(g.index?.count??g.attributes.position.count)/3})});
j.buffers[0].byteLength=length;const bin=Buffer.concat(chunks),binPad=Buffer.alloc((4-bin.length%4)%4),jsonBytes=Buffer.from(JSON.stringify(j)),jsonPad=Buffer.alloc((4-jsonBytes.length%4)%4,32),h=Buffer.alloc(20),bh=Buffer.alloc(8);h.writeUInt32LE(0x46546c67,0);h.writeUInt32LE(2,4);h.writeUInt32LE(20+jsonBytes.length+jsonPad.length+8+bin.length+binPad.length,8);h.writeUInt32LE(jsonBytes.length+jsonPad.length,12);h.writeUInt32LE(0x4e4f534a,16);bh.writeUInt32LE(bin.length+binPad.length,0);bh.writeUInt32LE(0x004e4942,4);const output=Buffer.concat([h,jsonBytes,jsonPad,bh,bin,binPad]);fs.writeFileSync(out+'/static-atlas-m6.glb',output);
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');const unchanged=[];for(let n=0;n<src.json.nodes.length;n++){const node=src.json.nodes[n];if(jawNodeIndices.has(n)||modified.some(m=>m.node===node.name))continue;const next=j.nodes[nodeRemap.get(n)];if(JSON.stringify(node)!==JSON.stringify(next))throw Error('Untouched node changed '+node.name);if(JSON.stringify(src.json.meshes[node.mesh])!==JSON.stringify(j.meshes[node.mesh]))throw Error('Untouched mesh changed '+node.name);unchanged.push(node.name);}
if(!bin.subarray(0,src.json.buffers[0].byteLength).equals(src.bin.subarray(0,src.json.buffers[0].byteLength)))throw Error('Original binary changed');const result={status:'PASS',source:inputs.static,sourceSHA256:hash(src.bytes),output:'static-atlas-m6.glb',outputSHA256:hash(output),displayOnly:true,staticHumanUnchanged:true,originalBinaryPreserved:true,originalBinaryBytes:src.json.buffers[0].byteLength,originalBinarySHA256:hash(src.bin.subarray(0,src.json.buffers[0].byteLength)),removedNodeNames,modifiedNodes:modified,oldPalmTriangles:oldPalmTriangleCount,matchedRemovedTriangles:removedMatched,unmatchedTriangles:missing,triangleVertexMatchToleranceMetres:2e-6,maxMatchedVertexErrorMetres:maxMatchedVertexError,addedNodes:added,unchangedOriginalNodes:unchanged,unchangedOriginalNodeCount:unchanged.length,activeNodeCount:j.scenes[j.scene??0].nodes.length,bakedGrip:grip,bytes:output.length,note:'Old disconnected accessor/mesh descriptors remain as unreferenced archived bytes to preserve every original vertex/normal/UV/material buffer. Four two-jaw/pad nodes are removed entirely. Only matched palm/flange triangles are omitted from four shared-material primitives. Every added A04 mesh has module, side and a supported static layer. No CAD source or checkout modified.'};fs.writeFileSync(out+'/static-m6-validation.json',JSON.stringify(result,null,2));console.log(JSON.stringify({...result,addedNodes:added.length,unchangedOriginalNodes:undefined},null,2));
// Load the final GLB with the same loader used by the site and verify active tree.
const finalScene=await load(readGLB(out+'/static-atlas-m6.glb'));let actual=0,oldFinger=0,newFinger=0;finalScene.traverse(o=>{if(o.isMesh){actual++;if(o.name.includes('PARALLEL_JAW')||removedNodeNames.includes(o.name))oldFinger++;if(o.name.startsWith('STATIC_M6__'))newFinger++;}});if(oldFinger||newFinger!==added.length)throw Error(`Final scene mismatch ${oldFinger}/${newFinger}`);console.log(JSON.stringify({finalLoader:'PASS',actualMeshCount:actual,activeNewMeshes:newFinger,oldJawMeshes:oldFinger}));
